"""added foreign keys to message, user, and room

Revision ID: deaaeba9e6ec
Revises: 9e8a19e7d452
Create Date: 2022-03-10 16:00:33.010368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deaaeba9e6ec'
down_revision = '9e8a19e7d452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'room', ['room_id'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'room_id')
    op.drop_column('message', 'sender_id')
    # ### end Alembic commands ###
